### PR TITLE
TTS: Implement speech queueing on macOS

### PR DESCRIPTION
**Pull request by criezy**
In case you have not seen it before, when you merge a pull request you have an option to rebase, which will prevent the creation of a merge commit. If this is disabled for you, you may need to enable the option in your fork settings.
https://help.github.com/en/articles/merging-a-pull-request#merging-a-pull-request-on-github
https://help.github.com/en/articles/configuring-commit-rebasing-for-pull-requests

### CODE REVIEW

**Comment by criezy** [comment]
By the way I tested queueing the tooltip speech instead of dropping it (so that I could test that all three options work properly), and the result was quite nice I think. So we could consider changing it. And maybe the OSD speech should be queued as well (but I didn't try that, so this is just speculative).

**Comment by vyzigold** [comment]
I also tested queueing on tooltips :D. I don't know about queueing OSD messages, when I tested the TTS on them, I configured an unusable port for cloud, which triggered the OSD message immediately after clicking the Run Server button and since it is an immediate response of ScummVM, it makes sense to me to read it as soon as possible, if the user needs to hear the whole button text, he would probably wait before clicking it. But just greping "OSD" in the whole ScummVM probably doesn't give me the right idea about where else and how else the OSD is used, so if it makes sense to queue them to you, I will queue them. As for the tooltips, if we queue them, what if an OSD message appears after triggering it with a button click, the user stays on top of the button the whole time the OSD is read, but moves the mouse only slightly (still on top of the button) a few times and every time a tooltip appears (the same tooltip), that might queue a lot of the same tooltips behind each other, which probably wouldn't sound good. I could probably remember the last message in queue and don't add the same message to the queue, but there might be a usecase (maybe in some engine), where it is useful to read the same message multiple times. I think just dropping them is safer.

**Comment by criezy** [comment]
After a bit more thinking, I think indeed it makes more sense to read the OSD messages immediately since most of the time they will result from a user action.

And we could indeed add some actions such as INTERRUPT_NO_REPEAT (so that if the text is the same as the one currently being spoken, it is dropped instead of interrupting to start speaking it again - we might actually want to make that the default action) and QUEUE_NO_REPEAT (that would only queue the message if it is not the same as the last message in the queue, or if there if the queue is empty the message currently being spoken).

By the way it would be good to add some documentation for the Action enum values (for example add them to the documentation of the say function).

**Comment by criezy** [comment]
Another `by the way`: I was also thinking it might be a good idea to add a set of tests in the `testbed` engine to test the various TextToSpeechManager options all in one place. The `testbed` engine is there precisely to test backend implementations.

To use the testbed engine:
1. You need to explicitly enable it during configure (`--enable-engine=testbed`) as by default it is not compiled
2. In the ScummVM launcher use `Add Game` and navigate to `dists/engine-data/testbed-audiocd-files/` in your ScummVM source code,

**Comment by vyzigold** [comment]
I was actually thinking, that it would be cool to have some test for this and for the encoding too, but I didn't know there is a testbed engine. I added some tts tests to the testbed engine and I actually discovered, that in both, the linux and the windows implementation the state (isSpeaking, isReady, ...) is quite buggy, but I think I fixed it and it seems to be working. I added the INTERRUPT_NO_REPEAT and QUEUE_NO_REPEAT actions and I made the INTERRUPT_NO_REPEAT action the default. I will write some tests for them the first thing tomorrow.

**Pull request merged**
