### PR TITLE
Some TestBed and macOS TTS changes

### PR DESCRIPTION
**Pull request by criezy**
I moved the TTS tests in TestBed after what I think are more critical components for a backend (for example graphics, events). And I also added event polling to the while loops when speaking to avoid lockup (due the the state synchronisation with the macOS speech synthesizer requiring event processing).

In the macOS speech synthesiser I have now implemented the NO_REPEAT actions and fixed all the issues found by the TestBed tests (mostly related to the fact that the macOS speech synthesizer is run asynchronously, and that for example immediately after requesting something to be spoken, the isSpeaking state is not yet true as it has not yet started to speak).

I am also wondering if maybe we could more the TTS options to the Misc tab instead of adding a Accessibility tab since there is not a lot of options in that tab. But that is a question that could be asked in the pull request as I am not sure what is best there.

Overall the state seems pretty solid now. Do you see anything more that needs to be done before you open a pull request?

### CODE REVIEW

**Comment by vyzigold** [comment]
I created the Accessibility tab, because I saw on the GSoC ideas page, that there is a possibility to come up with some other accessibility options, so I thought, that this could be useful in the future, but I will ask in the pull request, what others think is better.

I think the state is indeed pretty solid. I fixed everything, that I didn't manage to fix on friday and I added documentations of getVoiceIndicesByGender() and Actions (in say()). There might be one more thing. On Windows, I had to rewrite some parts of sphelper.h, so I created sphelper-scummvm.h, which is the original sphelper.h with some of my alterations, but the Microsoft's code (parts I didn't touch) compiles with several warnings. Should I try to fix the warnings, or is it better to stay as close to the original as possible (so that maybe in the future if there is a new version of SAPI and with it a new version of sphelper.h, it might be easier to transition to it). Other than that, I don't see anything more to do.

**Comment by vyzigold** [comment]
One more thing, I see, the branch cannot be automaticaly merged to ScummVM's master branch. I guess, this is due to some GUI changes. What's the correct thing to do in such situation? Should I rebase this branch on top of the current ScummVM's master and resolve the merge conflicts before creating the pull request? Or is there something else, I should do?

**Comment by criezy** [comment]
Yes, the correct way is to rebase on top of master and resolve the conflicts that pop up. And then you can create the pull request.

For the sphelper.h, I would tend to keep it as close to the original as possible, but that is something you can ask on the pull request as well. Also you might want to clearly indicate in the file the parts that you modified and why.

I also noticed that I implemented INTERRUPT_NO_REPEAT slightly differently from what you documented and implemented. I am checking the speech that is currently being spoken (even if the queue is not empty) and always emptying the queue. So basically the behaviour is the same as INTERRUPT, except that is the speech we want is already being spoken it does not start over. I can change my implementation, but it seems maybe a bit more logical than what is documented.
```
say("This is the first sentence");
say("This is the second sentence", QUEUE);
g_system->delayMillis(1000);
say("This is the first sentence", INTERRUPT_NO_REPEAT);
```
With my implementation it will say "This is the first sentence" once, and nothing else.
With what is documented it would start saying "This is the first sentence", interrupt it after 1s and start over.

**Comment by vyzigold** [comment]
Yes, this makes more sense. I thought only about simple use cases, like going inside and outside of a button in GUI (no QUEUED string in the middle).

**Comment by vyzigold** [comment]
I took a look at the INTERRUPT_NO_REPEAT action. Unfortunately I don't have enough control of the queue to implement this on Linux and probably even on Windows. On Linux, I use the speech-dispatcher's internal queue and I can only cancel everything, or nothing, so I cannot let the current speech finish and cancel the rest of the queue. I have my own copy of the queue, which i use when pausing and resuming, which is bugged in speech-dispatcher (at least in the version I am using), so I tried to start the speech one at a time (after a speech ends, I would start saying the next string in the queue). This didn't work, because the speech-dispatcher locked a mutex before calling my callback, by which it tells me the previous speech ended, and when trying to start a new speech, it tryed to lock the same mutex again, so it ended in a deadlock.

The only solution I see for this, is to rewrite the manager to use a different thread. So I wouldn't use the speech-dispatcher's internal queue at all and instead I would have a thread, that would periodicaly check if the previous speech finished and if needed, it would start the next speech from my queue, which I have full controll of.

I would probably have to rework the WindowsTextToSpeechManager similarly, because there again is a possibility to only cancel everything, so if I want to let the current speech finish and cancel everything else, I cannot use the SAPI's internal queue (which I am using now) and I have to move some parts of the Win ttsMan to a different thread to start a new speech from my own queue as needed.

Fortunately, I should have some time in the next 2 days to work on this.

**Pull request merged**
